runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /test
  static_dir: test


- url: /tasks/bookadded
  script: tasks.handler.jobApp
- url: /tasks/bookfinished
  script: tasks.handler.jobApp
- url: /tasks/bookinprogress
  script: tasks.handler.jobApp

- url: /.*
  script: init.app

libraries:
- name: django
  version: "1.4"